// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqssdknjlocoskafnptj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxc3Nka25qbG9jb3NrYWZucHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NjM5NjksImV4cCI6MjA3MzEzOTk2OX0.YvhwaH-tzxoj2McaG1vAeiaPyMmi2NqxDGGkpad-W8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});